<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-KD7B1SL" failures="1" tests="1" name="Test(failed)(failed)(failed)(failed)(failed)(failed)(failed)" time="13.571" errors="0" timestamp="2022-11-15T15:42:55 IST">
  <testcase classname="scripts.inVC_LoginPage" name="tc2" time="5.102">
    <failure type="java.lang.AssertionError" message="expected [https://staging.invc.vc/meeting] but found [https://staging.invc.vc/]">
      <![CDATA[java.lang.AssertionError: expected [https://staging.invc.vc/meeting] but found [https://staging.invc.vc/]
at scripts.inVC_LoginPage.tc2(inVC_LoginPage.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="scripts.inVC_LoginPage" name="tc4" time="0.0">
    <ignored/>
  </testcase> <!-- tc4 -->
  <testcase classname="scripts.inVC_LoginPage" name="tc1" time="0.0">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase classname="scripts.inVC_LoginPage" name="tc3" time="0.0">
    <ignored/>
  </testcase> <!-- tc3 -->
  <testcase classname="scripts.inVC_LoginPage" name="tc5" time="0.0">
    <ignored/>
  </testcase> <!-- tc5 -->
</testsuite> <!-- Test(failed)(failed)(failed)(failed)(failed)(failed)(failed) -->
